db:
  url: jdbc:mysql://26.3.4.81:3306/hr-syhz?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  username: hrSyhz
  password: hrSyhz@123
upms:
  url: jdbc:mysql://26.3.4.81:3306:3306/hr-upms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: hrUpms
  password: hrUpms@123
eureka:
  url: http://Nmghr:NMhr$123@192.168.3.4:7007/eureka/
file:
  path: /home/code/attachment/检验鉴定委托书.docx