db:
  url: jdbc:mysql://192.168.43.201:3306/hr-syhz?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: hrsyhz
  password: 12345678
upms:
  url: jdbc:mysql://192.168.43.201:3306/hr-upms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: hrupms
  password: 12345678
eureka:
  url: http://Nmghr:NMhr$123@192.168.3.4:7007/eureka/
  
file:
  path: D://111//检验鉴定委托书.docx