management.security.enabled: false
spring.jmx.enabled: false

server:
  port: 9002
  servlet:
    contextPath: /syhz

spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  application:
    name: syhz-api
  profiles:
    active: dev
  datasource:
    separator: ;;
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initial-size: 2
    maximum-pool-size: 10
    connection-timeout: 5000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    continue-on-error: true
    initialization-mode: always
  slave:
   datasource:
      names: hrupms
      hrupms:
        separator: ;;
        url: ${upms.url}
        username: ${upms.username}
        password: ${upms.password}
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${eureka.url}
    healthcheck:
      enabled: false #开启健康检查
    fetchRegistry: false
    registry-fetch-interval-seconds: 60 #获取注册信息的时间间隔（s），默认为30秒
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
    lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
file:
    path: ${file.path}
    
lanxin:
  reqUrl: http://staging430.t.lanxin.cn/cgi-bin/token
  grantType: client_credential
  appid: 101783
  secret: 2TMFJ4ZgHGZPTwE_RW
  linkmsg: http://192.168.1.104:8080/syh.html?
  lxApi: https://staging430.t.lanxin.cn/cgi-bin/message/custom/send?rand=97
  roleCode: sys_admin