db:
  url: jdbc:mysql://192.168.42.230:3306/shanxi-hsyz?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: hsyz
  password: 123456
upms:
  url: jdbc:mysql://192.168.42.230:3306/shanxi-upms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: shanxiupms
  password: 123456
eureka:
  url: http://Nmghr:NMhr$123@192.168.3.4:7007/eureka/
  
file:
  path: D://111//检验鉴定委托书.docx