management.security.enabled: false
spring.jmx.enabled: false

server:
  port: 9002
  servlet:
    contextPath: /syhz

spring:
  activemq:
    broker-url: ${mq.url}
    user: ${mq.name}
    password: ${mq.password}
    pool:
      enabled: false
    packages: #是否信任所有包
      trust-all: true
  jms: #默认情况下，activemq使用的是queue模式，如果要使用topic模式，必须设置为true
    pub-sub-domain: false
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  application:
    name: syhz-api
  profiles:
    active: test
  datasource:
    separator: ;;
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initial-size: 2
    maximum-pool-size: 10
    connection-timeout: 5000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    continue-on-error: true
    initialization-mode: always
  slave:
   datasource:
      names: hrupms
      hrupms:
        separator: ;;
        url: ${upms.url}
        username: ${upms.username}
        password: ${upms.password}
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  elasticsearch: 
    bboss:
      elasticPassword: changeme
      elasticUser: elastic
      elasticsearch: 
        dateFormat: yyyy.MM.dd
        discoverHost: false
        rest:
          hostNames: ${elasticsearch.hostNames}
        scrollBlockedWaitTimeout: 0
        scrollThreadCount: 200
        scrollThreadQueue: 200
        showTemplate: true
        sliceScrollBlockedWaitTimeout: 0
        sliceScrollThreadCount: 100
        sliceScrollThreadQueue: 100
        timeZone: Asia/Shanghai
      http:
        connectionRequestTimeout: 5000
        customHttpRequestRetryHandler: org.frameworkset.spi.remote.http.ConnectionResetHttpRequestRetryHandler
        defaultMaxPerRoute: 200
        hostnameVerifier:
        keepAlive: 3600000
        keyPassword:
        keystore:
        maxHeaderCount: 200
        maxLineLength: -1
        maxTotal: 400
        retryTime: 1
        retryInterval: 1000
        soKeepAlive: false
        soReuseAddress: false
        staleConnectionCheckEnabled: false
        timeToLive: 3600000
        timeoutConnection: 5000
        timeoutSocket: 5000
        validateAfterInactivity: 2000
#      db:
#        driver: com.mysql.jdbc.Driver
#        name: test
#        password: 123456
#        url: jdbc:mysql://localhost:3306/bboss
#        usePool: false
#        user: root
#        validateSQL: select 1
      dslfile:
        refreshInterval: -1

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${eureka.url}
    healthcheck:
      enabled: false #开启健康检查
    fetchRegistry: false
    registry-fetch-interval-seconds: 60 #获取注册信息的时间间隔（s），默认为30秒
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
    lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
file:
    path: ${file.path}
    
lanxin:
  reqUrl: http://staging430.t.lanxin.cn/cgi-bin/token
  grantType: client_credential
  appid: 101783
  secret: 2TMFJ4ZgHGZPTwE_RW
  linkmsg: http://192.168.1.104:8080/syh.html?
  lxApi: https://staging430.t.lanxin.cn/cgi-bin/message/custom/send?rand=97
  roleCode: sys_admin
  runFlag: ${lanxin.runFlag}